export { default as Home } from './Home.vue'
export { default as SearchResults } from './SearchResults.vue'
export { default as MangaInfo } from './MangaInfo.vue'
export { default as Reader } from './Reader.vue'
export { default as History } from './History.vue'
export { default as Bookmarks } from './Bookmarks.vue'
